
spring.profiles.active=prod

server.address=0.0.0.0
server.port=8080

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html

# 1. El nombre oficial con el que tu proyecto se anotará en el directorio
spring.application.name=juegos-service

# 2. La dirección web donde el Servidor Eureka está escuchando
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/