spring.application.name=JUEGOS
spring.profiles.active=prod

server.address=0.0.0.0
server.port=8080

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html